export const FETCH_PRODUCTS_DETAILS_SUCCESS = "FETCH_PRODUCTS_DETAILS_SUCCESS";
export const FETCH_PRODUCTS_DETAILS_ERROR = "FETCH_PRODUCTS_DETAILS_ERROR";
export const API_SUCCESS = "API_SUCCESS";
export const API_ERROR = "API_ERROR";
